In [11]:
import torch

device = 'cuda' if torch.cuda.is_available() else 'cpu'
block_size = 8
batch_size = 4

with open("george_washington.txt", 'r', encoding='utf-8') as f:
    text = f.read()

chars = sorted(set(text))
print(chars)
vocabulary_size = len(chars)

string_to_int = {ch:i for i, ch in enumerate(chars) }
int_to_string = {i: ch for i, ch in enumerate(chars) }
encode = lambda s: [string_to_int[c] for c in s]
decode = lambda l: "".join([int_to_string[i] for i in l])

data = torch.tensor(encode(text), dtype=torch.long)
print(data[:100])

n = int(0.8*len(data))
train_data = data[:n]
val_data = data[n:]

block_size = 8
batch_size = 2

def get_batch(split):
    data = train_data if split == 'train' else val_data
    ix = torch.randint(len(data) - block_size, (batch_size,))
    print(ix)
    x = torch.stack([data[i:i+block_size] for i in ix])
    y = torch.stack([data[i+1:i+block_size+1] for i in ix])
    x, y = x.to(device), y.to(device)
    return x, y

x, y = get_batch('train')
print('inputs')
print(x)
print('target')
print(y)


['\n', ' ', '!', '&', '(', ')', '*', ',', '-', '.', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9', ':', ';', '=', '>', '?', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z', '[', ']', '_', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', '{', '}', '£', 'Æ', 'æ', 'é', 'ê', 'ô', 'œ', '‘', '’', '“', '”']
tensor([ 0,  0,  0,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
         1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, 53, 31, 58, 68, 71, 60, 58,
         1, 47, 54, 72, 61, 62, 67, 60, 73, 68, 67, 53,  0,  0,  0,  1,  1,  1,
         1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
         1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, 26, 49,  0,  1,
         1,  1,  1,  1,  1,  1,  1,  1,  1,  1])
tensor([192817, 247877])
inputs
tensor([[58,  1, 76, 71, 62, 73, 72,  1],
        [3

In [ ]:
class BigramLanguageModel(nn.Model):
    def _init_(self, vocabulary_size):
        self.token_embedding_table = nn.Embedding(vocabulary_size, vocabulary_size)

    def forward(self, index, targets):
        logits = self.token_embedding_table(index)

        return logits

    